# Generated by Django 3.1.1 on 2021-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0002_auto_20210719_2209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virus",
            name="enveloped",
            field=models.BooleanField(blank=True),
        ),
    ]
