# Generated by Django 3.1.1 on 2021-07-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0004_auto_20210719_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virus",
            name="C6_36_cells",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="genome_length_nt",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="human_fatal_disease",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="vero_cells",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="veterinary_diseases",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="veterinary_fatal_diseases",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
