# Generated by Django 3.1.1 on 2021-07-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0005_auto_20210719_2213"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirusGenus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="virus",
            name="genus",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="arbovirus.virusgenus",
            ),
        ),
    ]
