# Generated by Django 3.1.1 on 2021-07-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0006_auto_20210719_2251"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virus",
            old_name="virus_name",
            new_name="name",
        ),
    ]
