# Generated by Django 3.1.1 on 2021-07-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arbovirus', '0007_auto_20210719_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='virus',
            name='family',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='arbovirus.virusfamily'),
        ),
    ]
