# Generated by Django 3.1.1 on 2021-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0010_disease"),
    ]

    operations = [
        migrations.AddField(
            model_name="virus",
            name="diseases",
            field=models.ManyToManyField(to="arbovirus.Disease"),
        ),
    ]
