# Generated by Django 3.1.1 on 2021-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0011_virus_diseases"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
    ]
