# Generated by Django 3.1.1 on 2021-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0012_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="virus",
            name="country",
            field=models.ManyToManyField(to="arbovirus.Country"),
        ),
    ]
