# Generated by Django 3.1.1 on 2021-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arbovirus", "0013_virus_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="VectorSpecies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("arthropod_type", models.TextField(blank=True, null=True)),
                ("genus", models.IntegerField(blank=True, null=True)),
                ("genome", models.BooleanField(blank=True, null=True)),
                ("reference_genome", models.TextField(blank=True, null=True)),
                ("genome_size", models.IntegerField(blank=True, null=True)),
                (
                    "survival_temperature_ranges",
                    models.TextField(blank=True, null=True),
                ),
                ("survival_humidity_percent", models.TextField(blank=True, null=True)),
                ("distribution", models.TextField(blank=True, null=True)),
                ("adult_life_expectancy_days", models.TextField(blank=True, null=True)),
                (
                    "anthropophilic_behaviour",
                    models.BooleanField(blank=True, null=True),
                ),
                ("eggs_viability_days", models.TextField(blank=True, null=True)),
                ("lifecycle_time_days", models.TextField(blank=True, null=True)),
                ("experimental_infection", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
