# Generated by Django 3.1.1 on 2021-08-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbovirus', '0016_auto_20210824_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borning',
            old_name='borne_type',
            new_name='name',
        ),
    ]
