# Generated by Django 3.1.1 on 2021-06-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_virus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='collection_date',
            field=models.TextField(default=''),
        ),
    ]
