# Generated by Django 4.2.17 on 2024-12-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arboverse_updated', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodmeal',
            table='arboviru_bloodmeal',
        ),
        migrations.AlterModelTable(
            name='borning',
            table='arbovirus_borning',
        ),
        migrations.AlterModelTable(
            name='country',
            table='arbovirus_country',
        ),
        migrations.AlterModelTable(
            name='disease',
            table='arbovirus_disease',
        ),
        migrations.AlterModelTable(
            name='feedingperiod',
            table='arbovirus_fedingperiod',
        ),
        migrations.AlterModelTable(
            name='habitat',
            table='arbovius_habitat',
        ),
        migrations.AlterModelTable(
            name='landscape',
            table='arboviru_landscape',
        ),
        migrations.AlterModelTable(
            name='location',
            table='arbovirs_location',
        ),
        migrations.AlterModelTable(
            name='vectorfamily',
            table='arbovirus_vectorfamily',
        ),
        migrations.AlterModelTable(
            name='vectorgenus',
            table='arbovirus_vectorgenus',
        ),
        migrations.AlterModelTable(
            name='vectororder',
            table='arbovirus_vectororder',
        ),
        migrations.AlterModelTable(
            name='vectorspecies',
            table='arbovirus_vectorspecies',
        ),
        migrations.AlterModelTable(
            name='vectorsubfamily',
            table='arbovirus__vecorsubfamily',
        ),
        migrations.AlterModelTable(
            name='virus',
            table='arbovirus_virus',
        ),
        migrations.AlterModelTable(
            name='virusfamily',
            table='arbovirus_virusfamily',
        ),
        migrations.AlterModelTable(
            name='virusgenus',
            table='arbovirus_virusgenus',
        ),
        migrations.AlterModelTable(
            name='virusvector',
            table='arbovirus_virusvector',
        ),
    ]
