# Generated by Django 4.2.18 on 2025-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bloodmeal",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="borning",
            options={"ordering": ["borne_type"]},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="disease",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="feedingperiod",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="habitat",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="landscape",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vectorfamily",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vectorgenus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vectororder",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vectorspecies",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vectorsubfamily",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="virus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="virusfamily",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="virusgenus",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="virusvector",
            options={"ordering": ["virus", "vector"]},
        ),
        migrations.AlterField(
            model_name="bloodmeal",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="borning",
            name="borne_type",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="feedingperiod",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="habitat",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="landscape",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="vectorfamily",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="vectorgenus",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="vectororder",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="vectorsubfamily",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="virus",
            name="name",
            field=models.TextField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="virusfamily",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="virusgenus",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
