# Generated by Django 4.2.18 on 2025-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "arboverse_updated",
            "0002_alter_bloodmeal_options_alter_borning_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datafile", models.FileField(upload_to="uploads/")),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["datafile"],
            },
        ),
    ]
