# Generated by Django 4.2.18 on 2025-01-23 21:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0003_dataupload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataupload",
            name="datafile",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location="/data"),
                upload_to="",
            ),
        ),
    ]
