# Generated by Django 4.2.17 on 2024-12-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arboverse_updated', '0003_alter_landscape_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodmeal',
            table='arbovirus_bloodmeal',
        ),
    ]
