# Generated by Django 4.2.18 on 2025-01-24 16:41

# Updated 2025-01-26 to remove this table as
# DataUpload replaced it and it is no longer
# needed.
#
# skr

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0004_alter_dataupload_datafile"),
    ]

    operations = [
    ]
