# Generated by Django 4.2.18 on 2025-01-26 20:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0006_alter_dataupload_datafile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datafile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/data"
                        ),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["datafile"],
            },
        ),
        migrations.AlterModelOptions(
            name="dataupload",
            options={},
        ),
        migrations.AlterField(
            model_name="dataupload",
            name="datafile",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/code/media"
                ),
                upload_to="",
            ),
        ),
    ]
