# Generated by Django 4.2.18 on 2025-01-27 15:56

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0007_datauploader_alter_dataupload_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="uploaded",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datauploader",
            name="datafile",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location="/media"),
                upload_to="",
            ),
        ),
    ]
