# Generated by Django 4.2.18 on 2025-01-27 17:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0008_dataupload_uploaded_alter_datauploader_datafile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataReload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "vectorfile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/code/media"
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "virusfile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/code/media"
                        ),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DataUpload",
        ),
        migrations.DeleteModel(
            name="DataUploader",
        ),
    ]
