# Generated by Django 4.2.18 on 2025-01-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("arboverse_updated", "0009_datareload_delete_dataupload_delete_datauploader"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={},
        ),
        migrations.AlterModelTable(
            name="bloodmeal",
            table="arboverse_updated_bloodmeal",
        ),
        migrations.AlterModelTable(
            name="borning",
            table="arboverse_updated_borning",
        ),
        migrations.AlterModelTable(
            name="disease",
            table="arboverse_updated_disease",
        ),
        migrations.AlterModelTable(
            name="feedingperiod",
            table="arboverse_updated_feedingperiod",
        ),
        migrations.AlterModelTable(
            name="virus",
            table="arboverse_updated_virus",
        ),
        migrations.AlterModelTable(
            name="virusfamily",
            table="arboverse_updated_virusfamily",
        ),
        migrations.AlterModelTable(
            name="virusgenus",
            table="arboverse_updated_virusgenus",
        ),
    ]
