# Generated by Django 4.2.18 on 2025-01-28 05:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "arboverse_updated",
            "0010_alter_country_options_alter_bloodmeal_table_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded", models.DateField(auto_now_add=True)),
                (
                    "datafile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/code/media"
                        ),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datafile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/media"
                        ),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["datafile"],
            },
        ),
        migrations.DeleteModel(
            name="DataReload",
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="bloodmeal",
            table=None,
        ),
        migrations.AlterModelTable(
            name="borning",
            table=None,
        ),
        migrations.AlterModelTable(
            name="disease",
            table=None,
        ),
        migrations.AlterModelTable(
            name="feedingperiod",
            table=None,
        ),
        migrations.AlterModelTable(
            name="virus",
            table=None,
        ),
        migrations.AlterModelTable(
            name="virusfamily",
            table=None,
        ),
        migrations.AlterModelTable(
            name="virusgenus",
            table=None,
        ),
    ]
