# Generated by Django 4.2.18 on 2025-01-28 15:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "arboverse_updated",
            "0011_dataupload_datauploader_delete_datareload_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataReload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "vectorfile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/code/media"
                        ),
                        upload_to="",
                    ),
                ),
                (
                    "virusfile",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/code/media"
                        ),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="DataUpload",
        ),
        migrations.DeleteModel(
            name="DataUploader",
        ),
        migrations.AlterModelOptions(
            name="country",
            options={},
        ),
        migrations.AlterModelTable(
            name="bloodmeal",
            table="arboverse_updated_bloodmeal",
        ),
        migrations.AlterModelTable(
            name="borning",
            table="arboverse_updated_borning",
        ),
        migrations.AlterModelTable(
            name="disease",
            table="arboverse_updated_disease",
        ),
        migrations.AlterModelTable(
            name="feedingperiod",
            table="arboverse_updated_feedingperiod",
        ),
        migrations.AlterModelTable(
            name="virus",
            table="arboverse_updated_virus",
        ),
        migrations.AlterModelTable(
            name="virusfamily",
            table="arboverse_updated_virusfamily",
        ),
        migrations.AlterModelTable(
            name="virusgenus",
            table="arboverse_updated_virusgenus",
        ),
    ]
