# Generated by Django 4.2.18 on 2025-01-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "arboverse_updated",
            "0012_datareload_delete_dataupload_delete_datauploader_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="habitat",
            table="arboverse_updated_habitat",
        ),
        migrations.AlterModelTable(
            name="landscape",
            table="arboverse_updated_landscape",
        ),
        migrations.AlterModelTable(
            name="location",
            table="arboverse_updated_location",
        ),
        migrations.AlterModelTable(
            name="vectorfamily",
            table="arboverse_updated_vectorfamily",
        ),
        migrations.AlterModelTable(
            name="vectorgenus",
            table="arboverse_updated_vectorgenus",
        ),
        migrations.AlterModelTable(
            name="vectororder",
            table="arboverse_updated_vectororder",
        ),
        migrations.AlterModelTable(
            name="vectorspecies",
            table="arboverse_updated_vectorspecies",
        ),
        migrations.AlterModelTable(
            name="vectorsubfamily",
            table="arboverse_updated_subfamily",
        ),
        migrations.AlterModelTable(
            name="virusvector",
            table="arboverse_updated_virusvector",
        ),
    ]
