# Generated by Django 4.2.17 on 2024-12-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arboverse_updated', '0002_alter_bloodmeal_table_alter_borning_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landscape',
            table='arbovirus_landscape',
        ),
    ]
